/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.iot.service;
import cn.zhuatech.iot.common.BusinessException; import cn.zhuatech.iot.dto.IotDto.*; import cn.zhuatech.iot.model.*; import cn.zhuatech.iot.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class IotService {
    private final DeviceTaskRepository orders; private final TelemetryRecordRepository reports; private final DeviceRepository device; private final AlarmEventRepository alarmEvents; private final CurrentUserService current;
    public IotService(DeviceTaskRepository orders,TelemetryRecordRepository reports,DeviceRepository device,AlarmEventRepository alarmEvents,CurrentUserService current){this.orders=orders;this.reports=reports;this.device=device;this.alarmEvents=alarmEvents;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getSiteCode();List<DeviceTask> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findBySiteCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<DeviceTaskView> deviceTasks(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){DeviceTask order=orders.findById(id).orElseThrow(()->new BusinessException("设备任务不存在"));if(order.getStatus()==DeviceTask.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("正常点位不能超过任务剩余点位");order.report(request.goodQty(),request.defectQty());reports.save(new TelemetryRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<DeviceTask> list){int planned=list.stream().mapToInt(DeviceTask::getPlannedQty).sum(),done=list.stream().mapToInt(DeviceTask::getCompletedQty).sum(),defects=list.stream().mapToInt(DeviceTask::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("任务点位",String.format("%,d",planned),list.size()+" 张设备任务","blue"),new Metric("任务完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("数据有效率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 个失败点位","warn"),new Metric("设备告警",device.countByStatus(Device.Status.ALARM)+"",alarmEvents.countByResult(AlarmEvent.Result.PENDING)+" 项待确认告警","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),device.findAllByOrderByCodeAsc().stream().map(e->new DeviceView(e.getCode(),e.getName(),e.getSite().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),alarmEvents.findTop10ByOrderByIdDesc().stream().map(i->new AlarmEventView(i.getAlarmEventNo(),i.getDeviceTask().getOrderNo(),i.getDeviceTask().getProductName(),i.getAlarmEventType(),i.getSampleQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private DeviceTaskView view(DeviceTask o){return new DeviceTaskView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getSite().getName(),o.getSite().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(DeviceTask o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
